### PR TITLE
fix: CheckBox, RadioButton and ToggleSwitch controls labels not matching like it should

### PR DESCRIPTION
**Pull request by Marc-Antoine-Soucy**
GitHub Issue (If applicable): #
https://github.com/unoplatform/Uno.Gallery/issues/901

## PR Type

What kind of change does this PR introduce?

- Bugfix

## Description
- Fix CheckBox, RadioButton, and ToggleSwitch controls labels not matching like it should
- Fix InteropServices.COMException - Cannot locate resource from 'ms-resource:///Files/FluentOverrides.xaml'
- Update Material/Cupertino packages

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tested on iOS.
- [X] Tested on Wasm.
- [X] Tested on Android.
- [X] Tested on Windows.
- [X] Tested in both **Light** and **Dark** themes.
- [X] Associated with an issue (GitHub or internal)

### CODE REVIEW

**Review by kazo0 — APPROVED** [review]

**Review by agneszitte — CHANGES_REQUESTED** [review]
I will double-check this after my changes in Uno.Themes for RadioButton / CheckBox update

**Comment by agneszitte** [comment]
I have pushed the latest changes in order to fix the issue. Okay on Windows, Wasm, and Skia.GTK
Waiting to sync with @kazo0 first for an issue for Android/iOS specifically related to Gallery app itself

**Comment by agneszitte** [comment]
> > I have pushed the latest changes in order to fix the issue. Okay on Windows, Wasm, and Skia.GTK Waiting to sync with @kazo0 first for an issue for Android/iOS specifically related to Gallery app itself
> 
> Related issue : #940

#940 fixed, PR ready for review

**Comment by agneszitte** [comment]
@Mergifyio backport legacy/4x

**Review by kazo0 — APPROVED** [review]

**Pull request merged**
