### PR TITLE
fix: Adjusting ToggleSwitch shadows details

### PR DESCRIPTION
**Pull request by eriklimakc**
GitHub Issue (If applicable): #931

## PR Type

What kind of change does this PR introduce?
- Bugfix

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested on iOS.
- [X] Tested on Wasm.
- [X] Tested on Android.
- [X] Tested on Windows.
- [X] Tested in both **Light** and **Dark** themes.
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by eriklimakc** [comment]
To be discussed:

In the Figma File we have different shadows for the Track in light mode, but not in dark mode. Do we keep it like this?
https://github.com/unoplatform/Uno.Gallery/blob/b1b65f8cb35a50713392120eb39caf6e42df0b47/Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml#L255

Same for the thumb, in light mode vs. dark mode:
https://github.com/unoplatform/Uno.Gallery/blob/b1b65f8cb35a50713392120eb39caf6e42df0b47/Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml#L508

In Light mode the Track has no opacity, and the thumb has 25%. But in Dark mode the Track has 25%, and the thumb has no opacity.
https://github.com/unoplatform/Uno.Gallery/blob/b1b65f8cb35a50713392120eb39caf6e42df0b47/Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml#L3783

cc @agneszitte @NVLudwig

**Comment by NVLudwig** [comment]
@eriklimakc Here is a summary of the changes for both Light and Dark Disabled Toggle Switches:
**No more Fills with transparency**
• Track color is SurfaceColor
• Thumb color is SurfaceColor
• Thumb Icon isOnSurfaceColor
**Component disabled state is presented at 30% opacity at the top level, thumb and track no longer have there own opacities**

This changes the look of the switch a bit but makes it more consistent across modes.

I hope this helps. Let me know if you have any questions

**Comment by eriklimakc** [comment]
Result after applying Ludwig's changes:

image

**Comment by agneszitte** [comment]
> @eriklimakc Here is a summary of the changes for both Light and Dark Disabled Toggle Switches: **No more Fills with transparency** • Track color is SurfaceColor • Thumb color is SurfaceColor • Thumb Icon isOnSurfaceColor **Component disabled state is presented at 30% opacity at the top level, thumb and track no longer have there own opacities**
> 
> This changes the look of the switch a bit but makes it more consistent across modes.
> 
> I hope this helps. Let me know if you have any questions.
> 
> FYI @Xiaoy312 this is not in the NTH branch
> 
> Figma link

FYI regarding the Light version update @NVLudwig 
Is this wanted like that or should be `OnSurfaceLowColor` for the last one like the others?
image

**Comment by NVLudwig** [comment]
@agneszitte It's corrected the pattern for Switch disabled is:
**Track** SurfaceVariantColor
**thumb** SurfaceColor
**Icon** OnSurface

Should work in Dark and Light modes the same way.

**Review by agneszitte — APPROVED** [review]

**Comment by agneszitte** [comment]
@Mergifyio backport legacy/4x

**Review by Xiaoy312 — APPROVED** [review]

**Comment by agneszitte** [comment]
Re-Open for backport PR

**Pull request merged**
