### PR TITLE
feat: Add Clipboard Sample Page

### PR DESCRIPTION
**Pull request by trungnt2910**
GitHub Issue (If applicable): #464

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

No Clipboard sample page.

## What is the new behavior?

A Clipboard sample page has been added.
The sample page includes:
- Copying and pasting of different data types (text, image, rich text, and files).
- Managing the Clipboard (flush, clear, and content changed).
- Code snippets.

The file example is disabled on every platform except UWP and Skia because there is no known support.
Furthermore, attempting to get the files from the `Assets` folder on some platforms (Android) throws an exception.

image

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested on iOS.
- [x] Tested on Wasm.
- [x] Tested on Android.
- [x] Tested on UWP.
- [x] Tested in both **Light** and **Dark** themes.
- [x] Associated with an issue (GitHub or internal)

## Other information

Note that the samples on WASM other than text won't work due to https://github.com/unoplatform/uno/issues/10032.

Because I don't own an iPhone, I cannot test the app on iOS, but it should work as I don't use any platform-specific code except on UWP and WASM.

Internal Issue (If applicable):

### CODE REVIEW

**Comment by trungnt2910** [comment]
Seems like a problem from your side. All three of my PRs have this issue:

```
deployment_token was not provided.
```

**Comment by MartinZikmund** [comment]
@trungnt2910 Indeed, seems adjustment is needed on the pipeline, will ask Jerome to check it

**Comment by trungnt2910** [comment]
Same issue:
```
deployment_token was not provided.
```

**Comment by trungnt2910** [comment]
Neither of these commits are related to static web apps, which is the one that's failing in the first place....

Also seems like Android is not configured properly:

```
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.301\tools\Xamarin.Android.Common.targets(2282,2): error MSB4044: The "AndroidSignPackage" task was not given a value for the required parameter "KeyStore". [D:\a\1\s\Uno.Gallery\Uno.Gallery.Mobile\Uno.Gallery.Mobile.csproj]
```

I also have my own CI for Android apps but I don't recall having to acquire a key in order to produce `.apk` files.

**Comment by jeromelaban** [comment]
Thanks for the feedback. The Azure Static Apps failure is not something we can fix. We're adjusting this PR until all the other checks are passing.

**Comment by jeromelaban** [comment]
Thanks for your contribution!

**Pull request merged**
