### PR TITLE
build: Update to net8.0 to fix canary

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

- Bugfix
- Feature
- Code style update (formatting)
- Refactoring (no functional changes, no api changes)
- Build or CI related changes
- Documentation content changes
- Project automation
- Other... Please describe:

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested on iOS.
- [ ] Tested on Wasm.
- [ ] Tested on Android.
- [ ] Tested on UWP.
- [ ] Tested in both **Light** and **Dark** themes.
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
@Youssef1313 the migration is already done in the single project branch

**Comment by Youssef1313** [comment]
@jeromelaban The other PR isn't yet complete, doesn't adjust the CI for example. This was meant to be a quicker change to get canary working again soon, and possibly will make the single project migrarion easier as the CI will be set up right with .NET 8

**Comment by agneszitte** [comment]
@Youssef1313 I think the goal would be to do this work on the https://github.com/unoplatform/Uno.Gallery/pull/1104 related changes. As the goal would be to migrate Gallery to single project as well. ([Related documentation](https://teams.microsoft.com/l/message/19:2f70f2e6c0a84549b5137ceda4b298a2@thread.tacv2/1713892312838?tenantId=a297d6c0-b635-41a3-b1e3-558efe71e413&groupId=f55cdec8-036b-4efa-8e1a-c4129ba9bf12&parentMessageId=1713892312838&teamName=Uno%20Platform&channelName=RnD%20-%20Tooling%20-%20Templates%20and%20Wizard&createdTime=1713892312838)).

**Comment by Youssef1313** [comment]
> @Youssef1313 I think the goal would be to do this work on the #1104 related changes. As the goal would be to migrate Gallery to single project as well. ([Related discussion](https://teams.microsoft.com/l/message/19:2f70f2e6c0a84549b5137ceda4b298a2@thread.tacv2/1713892312838?tenantId=a297d6c0-b635-41a3-b1e3-558efe71e413&groupId=f55cdec8-036b-4efa-8e1a-c4129ba9bf12&parentMessageId=1713892312838&teamName=Uno%20Platform&channelName=RnD%20-%20Tooling%20-%20Templates%20and%20Wizard&createdTime=1713892312838)).

I guess we can make it in two steps, first updating to net8.0, which is more important for now, then continue the single project migration (which will mostly build on top of the net8.0 update).

**Pull request merged**
