### PR TITLE
Update neumorphic styles

### LINKED ISSUE #960: [Neumorphism] update styles with changes from NTH branch
## What would you like to be added:
update existing neumorphic styles with changes/improvements from the [preview nice-to-have" branch](https://www.figma.com/file/yrIxOBFdnzGVCdgTcl0gsH/branch/RNv2Lj56I7cF2StwhXoBMB/Shadow-Playground?type=design&node-id=4338-31096&mode=design&t=DSEogTvCvC1f1nNs-0) of figma

### PR DESCRIPTION
**Pull request by Xiaoy312**
GitHub Issue (If applicable): closes #960

## PR Type
What kind of change does this PR introduce?
- Bugfix
- Other... Please describe: control styling

## What is the new behavior?
updated certain controls' neumorphic styles to the NTH branch.

## PR Checklist
Please check if your PR fulfills the following requirements:
- [x] Tested on Skia.GTK.
- [x] Tested on iOS.
- [ ] Tested on Wasm.
- [x] Tested on Android.
- [x] Tested on UWP.
- [x] Tested in both **Light** and **Dark** themes.
- [x] Associated with an issue (GitHub or internal)

### CODE REVIEW

**Comment by NVLudwig** [comment]
@Xiaoy312 Wow! Impressive work!

**Comment by Xiaoy312** [comment]
@kazo0 im still unable to merge this pr, 
due to ios ui tests constantly failing
which this pr should have no impact on

**Review by kazo0 — APPROVED** [review]

**Comment by kazo0** [comment]
@Xiaoy312 good to merge whenever

**Pull request merged**
