### PR TITLE
build: Fix some build warnings

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

- Bugfix
- Feature
- Code style update (formatting)
- Refactoring (no functional changes, no api changes)
- Build or CI related changes
- Documentation content changes
- Project automation
- Other... Please describe:

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested on iOS.
- [ ] Tested on Wasm.
- [ ] Tested on Android.
- [ ] Tested on UWP.
- [ ] Tested in both **Light** and **Dark** themes.
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by kazo0 — APPROVED** [review]

**Review by Xiaoy312 — APPROVED** [review]

**Review by agneszitte — APPROVED** [review]

**Comment by Youssef1313** [comment]
Error is unrelated to my change. Let's see if restarting will fix it.

**Pull request merged**
