### PR TITLE
feat: Add Neumorphic styles to Shadow Builder sample

### PR DESCRIPTION
**Pull request by kazo0**
fixes https://github.com/unoplatform/Uno.Gallery/issues/935

image

image

### CODE REVIEW

**Review by agneszitte — COMMENTED** [review]
For the TextBox at the moment (color for example but same for the others blur, offset...) the only way to see the color update when changing the Hex color would be to unfocus the TextBox (tested on Wasm). It is not updating the color when taping "Enter" for example. Not sure if we can add a simple way to update the color as the value is written?
image

**Review by agneszitte — COMMENTED** [review]
Also when removing the shadows, the previous shadows stays and are not gone
image

**Comment by kazo0** [comment]
> Also when removing the shadows, the previous shadows stay and are not gone image
> 
> Same reverse issue, having only one shadow by changing the color to update (because of the issue mentioned above), try to add more shadows after that and it will not update also. image

@agneszitte this should be fixed by https://github.com/unoplatform/uno.toolkit.ui/pull/806

**Comment by kazo0** [comment]
> For the TextBox at the moment (color for example but same for the others blur, offset...) the only way to see the color update when changing the Hex color would be to unfocus the TextBox (tested on Wasm). It is not updating the color when taping "Enter" for example. Not sure if we can add a simple way to update the color as the value is written? image

@agneszitte this should now work in the latest commit

**Review by jeromelaban — APPROVED** [review]

**Comment by agneszitte** [comment]
@Mergifyio backport legacy/4x

**Pull request merged**
