### PR TITLE
refactor: Add Chip/ChipGroup samples, remove BottomSheet and NavigationBar samples and update Uno packages to latest

### PR DESCRIPTION
**Pull request by agneszitte-nventive**
GitHub Issue (If applicable): #294 

## PR Type

What kind of change does this PR introduce?

- Missing sample

## What is the current behavior?

No Chip/ChipGroup Sample available in Uno.Gallery

## What is the new behavior?

Chip/ChipGroup Sample added in Uno.Gallery

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tested on iOS.
- [X] Tested on Wasm.
- [X] Tested on Android.
- [X] Tested on UWP.
- [X] Tested in both **Light** and **Dark** themes.
- [X] Associated with an issue (GitHub or internal)

### CODE REVIEW

**Comment by agneszitte-nventive** [comment]
> For tracking purposes, here is the breaking PR ([unoplatform/Uno.Themes#641](https://github.com/unoplatform/Uno.Themes/pull/641))

Latest code was pushed to reflect the breaking changes in Uno.Themes

**Review by kazo0 — APPROVED** [review]

**Comment by agneszitte-nventive** [comment]
**[PR ON HOLD]** 
For now, as Chip control will be moved to toolkit.

**Comment by agneszitte-nventive** [comment]
PR ready for review

**Review by ajpinedam — APPROVED** [review]
Looks good!

**Review by Xiaoy312 — APPROVED** [review]
most unit tests, within the same cs, follow a shared routine that you can pretty much extract to a method(targetName, propertyName1?, propertyValue1?, propName2, propValue2)

**Review by kazo0 — APPROVED** [review]

**Comment by agneszitte-nventive** [comment]
> most unit tests, within the same cs, follow a shared routine that you can pretty much extract to a method(targetName, propertyName1?, propertyValue1?, propName2, propValue2)

I will properly take care of the UI tests in another PR as it will be the same for other controls like Checkbox for example

**Pull request merged**
