### PR TITLE
Shadows showcase (refactor neumorphic styles, add shadow builder)

### PR DESCRIPTION
**Pull request by kazo0**
- Rework Shadow showcase to show one control at a time
- Add the Shadow Builder control sample

Default state:
image

Control selected:
image

### CODE REVIEW

**Review by agneszitte — APPROVED** [review]

**Comment by agneszitte** [comment]
@kazo0 the filled buttons need to be on top of a PrimaryBrush background to have the wanted Neumorphic effect please
Whereas the elevated buttons need to stay on top of a SurfaceBrush background
image

Cf. Figma
-Light
image
-Dark
image

**Comment by agneszitte** [comment]
Seems there is an issue for FAB
image

**Comment by agneszitte** [comment]
When switching from template to template issues like this one is happening
image

**Comment by agneszitte** [comment]
I think some layers can be excluded with XamlStyler for some samples (so you are only left with the controls themselves)
image

**Comment by NVLudwig** [comment]
Reviewed with this [link](https://white-field-08c5cf00f-903.eastus2.3.azurestaticapps.net/)

**Improved UX Suggestions**

1. Put the Shadow Calculator before the Component preview

image

2. Make the Dropdown stick to the top of the page as you scroll down
image

3. Have a control showing on page load (only if you implement suggestion 1), Perhaps TabBar

4. Edit and move Call to Action into the CompoBox. Because the CTA does not fit in mobile layouts we could shorten the text and place it before or inside the ComboBox, keep it nice and bold.
image

**Comment by NVLudwig** [comment]
Light theme Issues found with this [link](https://white-field-08c5cf00f-903.eastus2.3.azurestaticapps.net/)

1. On Safari there is an intermittent issue when drawing the TabBar states (hard to repro) as well as on browser refresh.
image
image

2. On any control, double-clicking outside of an enabled control triggers this unexpected state
image
image

3. At times the ComboBox changes state unexpectedly, it looks selected but does not respond to keyboard prompts as if unselected. This "Selected state" happens inconsistently.
image
image

4. Flyouts are not neomorphic
image

5. FAB flyout could have more relevant labels and a neomorphic style
image

**Comment by NVLudwig** [comment]
**ComboBox Light theme only**
The selected option should be a different color then the label, you can refer to TextBox with Input for Values

Light (incorrect)
image

Dark (Correct)
image

Buttons (Light Theme only)
Top left Shadow seems to be missing in the implementation of enabled filled buttons
and too large in the disabled states
Implemented
image

Expected
image

**Comment by NVLudwig** [comment]
Main site Toggle Switch no longer works in Safari

**Comment by NVLudwig** [comment]
1. Unexpected scroll happens when you use the combo box **(non blocking)**

https://github.com/unoplatform/Uno.Gallery/assets/29584087/2dcca510-825c-44c5-aeeb-44d795d1ec9b

2. Clicking the 1st Toggle buttons or 2nd toggle switch scrolls the screen back up to the top (regression this has been fixed in the past)

https://github.com/unoplatform/Uno.Gallery/assets/29584087/8282cef8-0a7f-4bed-a44b-3c567cc3dd08

3. Toggle Switch Thumbs (aka knobs) are the wrong colors (both Light and Dark)
implemented image expected 
image

**Comment by kazo0** [comment]
@Mergifyio backport legacy/4x

**Pull request merged**
