### PR TITLE
chore: Update Uno.Material and Uno.Cupertino

### PR DESCRIPTION
**Pull request by agneszitte-nventive**
GitHub Issue (If applicable): https://github.com/unoplatform/Uno.Themes/issues/574

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

[ToggleSwitch] Some states don't match Material Design guidelines

## What is the new behavior?

All states match Material Design guidelines for all platforms

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tested on iOS.
- [X] Tested on Wasm.
- [X] Tested on Android.
- [X] Tested on UWP.
- [X] Tested in both **Light** and **Dark** themes.
- [X] Associated with an issue (GitHub or internal)

### CODE REVIEW

**Review by jeromelaban — APPROVED** [review]

**Comment by jeromelaban** [comment]
If the build still fails, we need to push the [run timeout for the build](https://github.com/unoplatform/Uno.Samples/blob/04344bb0c465a09aebe866418485cdd8a618c308/.vsts-ci.yml#L3).

**Comment by agneszitte-nventive** [comment]
Build succeeded, merged @jeromelaban :)

**Pull request merged**
